# Generated by Django 3.1.1 on 2025-09-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20201001_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
